### ISSUE TITLE
Version conflict detected for Newtonsoft.Json

### ISSUE THREAD

**Issue by myusrn** [kirkone/KK.AspNetCore.EasyAuthAuthentication#10]
In my asp.net core 2.x web app project I added reference to the KK.AspNetCore.EasyAuthAuthentication nuget package after which I started getting the following build error in my .net core xunit test project.  While i can just do as it says i would suggest that this project's newtonsoft.json package reference use the same 11.0.2 that the current .net core functions v2 project template microsoft.net.sdk.functions package has a dependency on so adopters don't unnecessarily see this issue.  

To repro create new asp.net core 2.1 web app/api project, and a cloud/azure functions v2 project and an xunit test .net core project that references both of them.  Everything should build w/o error then add the KK nuget to the asp.net core 2.1 web app/api project and at that point the ouput window should show the xunit test project error shown below.

```
Error	NU1107	Version conflict detected for Newtonsoft.Json. Install/reference Newtonsoft.Json 12.0.1 directly to project MyXUnitTests to resolve this issue. 
 MyXUnitTests -> MyWebApp -> KK.AspNetCore.EasyAuthAuthentication 1.0.0 -> Newtonsoft.Json (>= 12.0.1) 
 MyXUnitTests -> MyFuncApp -> Microsoft.NET.Sdk.Functions 1.0.24 -> Newtonsoft.Json (= 11.0.2).	MyXUnitTests	
d:\temp\MyTestSln\MyXUnitTests\MyXUnitTests.csproj	1		
```

It would appear that simply changing the "src\KK.AspNetCore.EasyAuthAuthentication\KK.AspNetCore.EasyAuthAuthentication.csproj" line 
`<PackageReference Include="Newtonsoft.Json" Version="12.0.1" />`
to
`<PackageReference Include="Newtonsoft.Json" Version="11.0.2" />`
would resolve this provided you are not using any newtonsoft.json features in this middleware solution that only showed up after 11.0.2 release.

I tested the opening `%userprofile%\.nuget\packages\kk.aspnetcore.easyauthauthentication\1.0.0\kk.aspnetcore.easyauthauthentication.nuspec` and making the following edit after which the build error went away but runtime issue surface from what appears to be web app still looking for a 12.0.0 newtonsoft drop.
```
<!--<dependency id="Newtonsoft.Json" version="12.0.1" exclude="Build,Analyzers" />-->
<dependency id="Newtonsoft.Json" version="11.0.2" exclude="Build,Analyzers" />
```

**Comment by paule96** [comment]
can we close this issue? @kirkone @myusrn

**Comment by myusrn** [comment]
@paule96 yes it can be closed as @kirkone accepted the associated pull request.  Wasn't sure if you folks were leaving it open until a nuget package update popped out of your devops pipeline with the changes in place.

**Comment by myusrn** [comment]
I pulled the current 1.1.0 nuget package update and confirmed this resolved the need for me to explicitly pull in latest newtonsoft.json package reference in projects with microsoft.net.sdk.functions package reference living in same solution as asp.net core web api project that had KK.AspNetCore.EasyAuthAuthentication package reference.  So I will close this issue with this comment.
