### ISSUE TITLE
Can we publish this to nuget

### ISSUE THREAD

**Issue by paule96** [kirkone/KK.AspNetCore.EasyAuthAuthentication#2]
Hi @kirkone,

can you publish this to nuget. The the usage is much better for the rest of the world.

**Comment by kirkone** [comment]
Here you go: 
https://www.nuget.org/packages/KK.AspNetCore.EasyAuthAuthentication/

**Comment by kirkone** [comment]
I will update the readme asap

**Comment by paule96** [comment]
Yes please 👍 add some nice badges 🚀
