### ISSUE TITLE
v2 nuget release failed with 403 error

### ISSUE THREAD

**Issue by bfrengley** [kirkone/KK.AspNetCore.EasyAuthAuthentication#48]
The 2.0.0 release changes (#31) were merged in on June 10. The build and release succeeded for Alpha and Beta, but the Release step failed to push to nuget with a 403 error:

```
2020-06-22T17:26:09.0428259Z ##[error]The nuget command failed with exit code(1) and error(Response status code does not indicate success: 403 (The specified API key is invalid, has expired, or does not have permission to access the specified package.).
```
[(logs here)](https://dev.azure.com/kirkone/KK.AspNetCore.EasyAuthAuthentication/_releaseProgress?releaseId=60&_a=release-environment-logs&environmentId=163)

As a result, the latest version on nuget is still 1.1.0.

Was it intended that 2.0.0 should have successfully released to nuget, rather than just Alpha/Beta/Internal (all of which have succeeded)?

**Comment by paule96** [comment]
yes we know. Have you options to use the beta or Alpha channel? The builds are the same and can be found on [this feed](https://dev.azure.com/kirkone/KK.AspNetCore.EasyAuthAuthentication/_packaging?_a=feed&feed=KK.AspNetCore.EasyAuthAuthentication).

**Comment by kirkone** [comment]
should be fixed by now. Will be visible in a few minutes.
Sorry for the delay.

![image](https://user-images.githubusercontent.com/15778270/87872484-5aef8200-c9b9-11ea-9bb5-1c76c0aafd08.png)
