### ISSUE TITLE
not populating User/ClaimsPrincipal in native app oauth authorization header token request case

### ISSUE THREAD

**Issue by myusrn** [kirkone/KK.AspNetCore.EasyAuthAuthentication#7]
Works great for populating User/ClaimsPrincipal in easyauth browser agent openid connect session cookie secured request cases but not for native [ desktop/mobile/postman] app oauth authorization header token secured request case.  The latter is how all web api secured calls will typically be coming in.  

I think I've figured out what is going on here and have a branch of updates that addresses the issue.  One matter that jumped out is this code currently assumes an azurewebsites/.auth/me request will flow through it that can be used to create the GenericIdentity, GenericPrincipal and attach that to the this.Context.User object.   My guess what was happening is that only happens once in the case of openid connect browser client interaction after which a session cookie is created that takes care of all subsequent requests being authenticated.  For oauth native app interaction that isn't going to be the case as every request is secured using bearer token that EasyAuth flips into X-MS-* header values.  So the fix I have working for both cases looks for X-MS-TOKEN-AAD-ID-TOKEN and if found creates this.Context.User object from there.  

The upside here is there is no overhead of a GetAuthMe() network request happening ever except in the locahost case where you want it to happen to pull in a sample azurewebsites.net/.auth/me json output captured and saved off somewhere.  For now i'm having to pull it from a blob storage url because of issue i'm having with iisexpress serving .json file as noted in issue #8 .

Also found issue with extracting claims from json payload where authentication method [amr] and roles claim need to be handled as array and broken out into individual claim entries to match what happens in the wild.  That said getting unexpected User.IsInRole results even though I was able to confirm the following.  Perhaps you folks have run into this previously with your work on this web app easyauth middleware and know what might be causing the unexpected role check results.  Need it working especially for `[Authorize(Roles = "RoleUserIsKnownToHaveClaimFor")]` attribute setting to block entries into controllers or controller methods.

```
User.IsInRole("RoleUserIsKnownToHaveClaimFor") -> false
(User.FindFirst(ClaimTypes.Role))?.Value -> "RoleUserIsKnownToHaveClaimFor"
(User.Identity as ClaimsIdentity).RoleClaimType -> "http://schemas.microsoft.com/ws/2008/06/identity/claims/role"
(User.Identity as ClaimsIdentity).RoleClaimType == ClaimTypes.Role -> true
```

I'll create a fork with my proposed above changes addressing this issue if you all are interested in a review and update of them in order to eventually pull back into this repo and get nuget package updated published.

**Comment by paule96** [comment]
@myusrn please fork the repo and add your changes there. So we can take a look to this :)

**Comment by myusrn** [comment]
@paule96 was thinking I was working against internalazure devops repo, forgot about need to use fork to stage and initiate pull requests.  Just created fork [here](https://github.com/myusrn/KK.AspNetCore.EasyAuthAuthentication) with my proposed fixes and have tested on my system and gives me results for native app oauth authorization header bearer token case now in addition to browser client openid connect [oidc] case which unlike native app after first request is handled using easyauth oidc issued session cookie.  With update only localhost debugging wwwroot/.auth/me.json scenario involves network request versus other cases which now leverage easyauth provided X-MS-TOKEN-AAD-ID-TOKEN header contents.  

I have tested localhost f5 debug with just browser caller where wwwroot/.auth/me.json gets used and postman request where I include X-MS-CLIENT-PRINCIPAL-NAME, X-MS-CLIENT-PRINCIPAL-IDP, X-MS-CLIENT-PRINCIPAL and X-MS-TOKEN-AAD-ID-TOKEN headers from azurewebsites.net/api/values call where easyauth generates and includes those headers and more.  I have tested published case using browser caller and postman request [ and native app using msft authentication library (msal) ] included Authorization header contained bearer token.  My postman collection that you can use to repro localhost tests, as header data expiration is not an issue, can be found [here](https://www.getpostman.com/collections/c5db787893d77182f1eb).

If you haven't seen it or used it before here are my crib notes on using postman to acquire oauth token and use in Authorization header bearer token secured web api request which is covered in [this](https://www.bruttin.com/2017/11/21/azure-api-postman.html) post

postman | new request | authorization | type = inherit auth from parent -> oauth 2.0 | get new access token [ and later available tokens drop down ]
token name = {func or web app name} auth
grant type = authorization code
callback url = client app https://{client app name}/auth not urn:ietf:wg:oauth:2.0:oob or func/web app https://{func or web app}.azurewebsites.net/.auth/login/aad/callback redirect uri
auth url = https://login.microsoftonline.com/{tenantid}/oauth2/v2.0/authorize acquired from app registration | overview | endpoints | oauth 2.0 authorization endpoint (v2)
access token url = https://login.microsoftonline.com/{tenantid}/oauth2/v2.0/token acquired from app registration | overview | endpoints | oauth 2.0 token endpoint (v2)
client id = client app  or funct/web app  id
client secret = client app or func/web app secret
scope = {func or web app id}/user_impersonation where first have is required so that issued token has audience "aud" claim value of {func or web app id}
state = leave blank
client authentication = send client credentials in body vs send as basic auth header
request token | signin dialog and app consent or silent auth if credentials cached | use token | preview request | save

**Comment by myusrn** [comment]
**update on User.IsInRole\(\) behavior:** I've figured out why User.IsInRole\(\) wasn't working and with last pair of checkins now have the resulting User, User.Identity and UserIdentities results showing up with exact same types as the non-easyauth authentication middleware case.

**Comment by kirkone** [comment]
@myusrn Thanks for your help to get this sorted out. The new version is on [Nuget.org](https://www.nuget.org/packages/KK.AspNetCore.EasyAuthAuthentication/0.2.0)

**Comment by myusrn** [comment]
@kirkone and @paule96 nice work on the quick turn around with refactoring and updates to get this issue addressed.  I just used my test solution environment to yank the project reference to your work and swap in the new nuget package drop and both localhost as well as both published test passes [ browser openid connect (oidc) session cookie and native app/postman oauth bearer token ] all working.
