### ISSUE TITLE
localhost debugging option not working for me

### ISSUE THREAD

**Issue by myusrn** [kirkone/KK.AspNetCore.EasyAuthAuthentication#8]
Very happy to see the localhost debugging support option based on <easyauth enabled web app deployment>/.auth/me output saved to <web app project>/wwwroot/auth/me.json file.

I enabled this using the following code and when i did an f5 localhost debug i didn't not find within my controllers that User.IsAuthenticated = true nor did I find the expected User.Claims, User.IsInRole(), User.Identity.Name results I expected.  Tested using browser agent and native [ postman ] app web api requests. 

I'm taking /.auth/me output and verifying first with jsonlint.com that it's valid before placing in wwwroot/auth/me.json .  

```
private IHostingEnvironment env; private ILogger<Startup> log;

public void ConfigureServices(IServiceCollection services)
{
    services.AddLogging();

    services.AddAuthentication(
        options =>
        {
            options.DefaultAuthenticateScheme = EasyAuthAuthenticationDefaults.AuthenticationScheme;
            options.DefaultChallengeScheme = EasyAuthAuthenticationDefaults.AuthenticationScheme;
        }
    ).AddEasyAuth(
        options =>
        {
            if (env.IsDevelopment())
            {
                log.LogInformation($"in ConfigureServices where env.IsDevelopment = {env.IsDevelopment()} and so assigning test data to options.AuthEndpoint");
                options.AuthEndpoint = "auth/me.json";
            }
        }
    );

    services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_1);
}

public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILogger<Startup> log)
{
    this.env = env; this.log = log;
    log.LogInformation($"in Configure where env.IsDevelopment = {env.IsDevelopment()}");
    . 
    .  .
    .  .  .
}

```

**Comment by myusrn** [comment]
closing as it looks like this was arising due to startup.cs missing a app.UseStaticFiles(); that would successful reading wwwroot/auth/me.json dummy data.

**Comment by kirkone** [comment]
Thanks for the hint.
I added this to the Readme
